name: "example/test"
on:
  push

jobs:
  run-test:
    name: "run library tests on ubuntu"
    runs-on: ubuntu-20.04
    steps:
      - name: install Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: checkout
        uses: actions/checkout@v2

      - name: cache wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-

      - name: cache library
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-cache-

      - name: run test
        run: ./gradlew test

      - name: store results
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test-results
          path: |
            lib/build/reports/
